site_name: ZZP Chef gebruikers documentatie
repo_url: https://github.com/zzpchef/ZZP-Chef
site_description: Gebruikers documentatie voor ZZP Chef gebruikers.
site_author: Folkert Jongbloed
theme:  
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'light blue'  
  logo:
    icon: 'cloud'  
  language: 'nl'

pages:
- Home: index.md
- Account:
  - Profiel: account/profiel.md
  - Factuur: account/factuur.md
- Organisaties:
  - Overzicht: organisaties/overzicht.md
  - Details: organisaties/details.md
- Projecten:
  - Overzicht: projecten/overzicht.md
  - Details: projecten/details.md
- Tarieven:
  - Overzicht: tarieven/overzicht.md
  - Details: tarieven/details.md
- Facturen:
  - Overzicht: facturen/overzicht.md
  - Details: facturen/details.md
  - Versturen: facturen/versturen.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - toc:
      permalink: false
  - pymdownx.highlight:
      guess_lang: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.superfences:
      css_class: codehilite
  - pymdownx.inlinehilite:
      css_class: codehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
